### ISSUE TITLE
data base glitch in portal 

### ISSUE THREAD

**Issue by befriedman** [ActiveBrainAtlas2/activebrainatlasadmin#219]
Database issue

A search for DK 109 urls- (to check to see if this case had been added to data base)
In error this led to DK 79 urls with ids 
729
678
676

**Comment by drinehart1** [comment]
![screen1](https://github.com/ActiveBrainAtlas2/activebrainatlasadmin/assets/25622382/21ba8481-c71f-4b5a-b6ab-ab1e93e5c3d4)

The search results (screenshot attached) shows this behavior.  I'm unclear at this point if this is actually a bug or feature since the text '109' appears in description of DK79 brains.  A targeted search for DK109 results in single result.

Should search continue to be 'global' or restricted to just animal id?

**Comment by befriedman** [comment]
I don't know what this is referring to -
maybe paste text from github issue tracker?

________________________________

**Comment by drinehart1** [comment]
I added additional documentation to existing issue so it will be easier to resolve.

**Comment by eddyod** [comment]
This is not a bug. If you want to search for DK109, don't put a space in the search query. When you put in a space it wll search the comments for 'DK' and '109' hence the results Beth got.
